apiVersion: apps/v1
kind: Deployment
metadata:
  name: upstream
  labels:
    app: upstream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upstream
  template:
    metadata:
      labels:
        app: upstream
    spec:
      containers:
      - name: upstream
        image: kubeicon-upstream:3
        ports:
        - containerPort: 8080